"""Removed nationality field from Team

Revision ID: 2188f97668f8
Revises: 263ea7444c93
Create Date: 2025-03-07 18:04:08.932946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2188f97668f8"
down_revision: Union[str, None] = "263ea7444c93"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("teams", sa.Column("webpage_url", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("teams", "webpage_url")
    # ### end Alembic commands ###
