"""added 'time_to_check_answer' to the SideBet model

Revision ID: 23288a90ef85
Revises: 8b18eb56a24e
Create Date: 2025-03-21 14:03:14.699083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "23288a90ef85"
down_revision: Union[str, None] = "8b18eb56a24e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "side_bets", sa.Column("time_to_check_answer", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("side_bets", "time_to_check_answer")
    # ### end Alembic commands ###
