"""replace game table into game_new

Revision ID: 23f76a990237
Revises: 31716f9dd590
Create Date: 2025-03-29 14:58:24.865751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "23f76a990237"
down_revision: Union[str, None] = "31716f9dd590"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_games_new_id", table_name="games_new")
    op.drop_table("games_new")
    op.add_column("games", sa.Column("stadium", sa.String(), nullable=True))
    op.drop_column("games", "stage")
    op.drop_column("games", "gameday")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "games", sa.Column("gameday", sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "games", sa.Column("stage", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.drop_column("games", "stadium")
    op.create_table(
        "games_new",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("team1", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("team2", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "match_time", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "game_state",
            postgresql.ENUM("upcoming", "ongoing", "history", name="gamestate"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("score_team1", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("score_team2", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "penalty_score_team1", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "penalty_score_team2", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column("game_winner", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "team1_odds",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "team2_odds",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "draw_odds",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("stadium", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name="games_new_pkey"),
    )
    op.create_index("ix_games_new_id", "games_new", ["id"], unique=False)
    # ### end Alembic commands ###
