"""Removed nationality field from Team

Revision ID: 263ea7444c93
Revises: 7d392e23ebe6
Create Date: 2025-03-07 17:14:27.151769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "263ea7444c93"
down_revision: Union[str, None] = "7d392e23ebe6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("teams", "nationality")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "teams",
        sa.Column("nationality", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
