"""added stadium to game model and removed stage and gameday

Revision ID: 31716f9dd590
Revises: fa80d10f5ddc
Create Date: 2025-03-27 14:53:20.102385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "31716f9dd590"
down_revision: Union[str, None] = "fa80d10f5ddc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("games_new", sa.Column("stadium", sa.String(), nullable=True))
    op.drop_column("games_new", "gameday")
    op.drop_column("games_new", "stage")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "games_new",
        sa.Column("stage", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "games_new",
        sa.Column("gameday", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_column("games_new", "stadium")
    # ### end Alembic commands ###
