"""Add points_added flag to bets

Revision ID: 4b8f90ef95bc
Revises: 651e9f9428a6
Create Date: 2025-03-05 15:35:01.389852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4b8f90ef95bc"
down_revision: Union[str, None] = "651e9f9428a6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Use server_default to set a default value for existing rows on column creation
    op.add_column(
        "bets",
        sa.Column(
            "points_granted",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("false"),
        ),
    )
    # After setting default, alter column to not have a server default anymore if desired
    op.alter_column("bets", "points_granted", server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bets", "points_granted")
    # ### end Alembic commands ###
