"""Added Teams and Players tables

Revision ID: 7d392e23ebe6
Revises: 7f3313f01b1d
Create Date: 2025-03-07 16:48:26.448032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7d392e23ebe6"
down_revision: Union[str, None] = "7f3313f01b1d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
