"""Added Teams stats fields

Revision ID: d9936aae4f6a
Revises: 2188f97668f8
Create Date: 2025-03-10 11:52:02.215200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d9936aae4f6a"
down_revision: Union[str, None] = "2188f97668f8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("teams", sa.Column("stats", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("teams", "stats")
    # ### end Alembic commands ###
