"""Added group_picture and description to BettingLeague

Revision ID: e1755ddb26d8
Revises: e7d4f1db2d49
Create Date: 2025-02-24 12:29:02.011128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e1755ddb26d8"
down_revision: Union[str, None] = "e7d4f1db2d49"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("betting_leagues", sa.Column("description", sa.Text(), nullable=True))
    op.add_column(
        "betting_leagues", sa.Column("group_picture", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("betting_leagues", "group_picture")
    op.drop_column("betting_leagues", "description")
    # ### end Alembic commands ###
