"""Added betting league posts and a posts field for the betting league model

Revision ID: f6fae560567d
Revises: e1755ddb26d8
Create Date: 2025-02-27 15:57:58.640627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f6fae560567d"
down_revision: Union[str, None] = "e1755ddb26d8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("betting_leagues", sa.Column("posts", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("betting_leagues", "posts")
    # ### end Alembic commands ###
