const TEAM_LOGOS = {
    "Borussia Dortmund": "/assets/team_logos/Dortmund.png",
    "Sporting Lisbon": "/assets/team_logos/Sporting.png",
    "Manchester City": "/assets/team_logos/Manchester_City.png",
    "Real Madrid": "/assets/team_logos/Real_Madrid.png",
    "Barcelona": "/assets/team_logos/Barcelona.png",
    "Paris Saint Germain": "/assets/team_logos/Paris_Saint-Germain.png",
    "Atalanta": "/assets/team_logos/Atalanta.png",
    "Juventus": "/assets/team_logos/Juventus.png",
    "Bayern München": "/assets/team_logos/Bayren_Munich.png",
    "Liverpool": "/assets/team_logos/Liverpool.png",
    "Arsenal": "/assets/team_logos/Arsenal.png",
    "AC Milan": "/assets/team_logos/AC_Milan.png",
    "Atletico Madrid": "/assets/team_logos/Atletico_Madrid.png",
    "Benfica": "/assets/team_logos/Benfica.png",
    "Porto": "/assets/team_logos/Porto.png",
    "Stuttgart": "/assets/team_logos/Stuttgart.png",
    "Feyenoord": "/assets/team_logos/Feyenoord.png",
    "RB Leipzig": "/assets/team_logos/RB_Leipzig.png",
    "PSV Eindhoven": "/assets/team_logos/PSV_Eindhoven.png",
    "Bologna": "/assets/team_logos/Bologna.png",
    "Sparta Prague": "/assets/team_logos/Sparta_Prague.png",
    "Celtic": "/assets/team_logos/Celtic.png",
    "Lille": "/assets/team_logos/Lille.png",
    "Inter": "/assets/team_logos/Inter.png",
    "Young Boys": "/assets/team_logos/Young_Boys.png",
    "Aston Villa": "/assets/team_logos/Aston_Villa.png",
    "Monaco": "/assets/team_logos/Monaco.png",
    "Dinamo Zagreb": "/assets/team_logos/Dinamo_Zagreb.png",
    "RB Salzburg": "/assets/team_logos/RB_Salzburg.png",
    "Slovan Bratislava": "/assets/team_logos/Slovan_Bratislava.png",
    "Shakhtar Donetsk": "/assets/team_logos/Shakhatar_Donetsk.png",
    "Girona": "/assets/team_logos/Girona.png",
    "Club Brugge": "/assets/team_logos/Club_Brugge.png",
    "Bayren Leverkusen": "/assets/team_logos/Bayren_Leverkusen.png",
    "Red Star": "/assets/team_logos/Red_Star.png",
    "Strum Graz": "/assets/team_logos/Strum_Graz.png",
    "Brest": "/assets/team_logos/Brest.png",
    "Default": "/assets/team_logos/default_logo.png"
}
export default TEAM_LOGOS;  