// frontend/src/constants/TeamLogos.js
const basePath = process.env.REACT_APP_PUBLIC_ASSETS_PATH || '/assets/team_logos/';

const TEAM_LOGOS = {
    "Borussia Dortmund": `${basePath}Dortmund.png`,
    "Sporting Lisbon": `${basePath}Sporting.png`,
    "Manchester City": `${basePath}Manchester_City.png`,
    "Real Madrid": `${basePath}Real_Madrid.png`,
    "Barcelona": `${basePath}Barcelona.png`,
    "Paris Saint Germain": `${basePath}Paris_Saint-Germain.png`,
    "Atalanta": `${basePath}Atalanta.png`,
    "Juventus": `${basePath}Juventus.png`,
    "Bayern München": `${basePath}Bayren_Munich.png`,
    "Liverpool": `${basePath}Liverpool.png`,
    "Arsenal": `${basePath}Arsenal.png`,
    "AC Milan": `${basePath}AC_Milan.png`,
    "Atletico Madrid": `${basePath}Atletico_Madrid.png`,
    "Benfica": `${basePath}Benfica.png`,
    "Porto": `${basePath}Porto.png`,
    "Stuttgart": `${basePath}Stuttgart.png`,
    "Feyenoord": `${basePath}Feyenoord.png`,
    "RB Leipzig": `${basePath}RB_Leipzig.png`,
    "PSV Eindhoven": `${basePath}PSV_Eindhoven.png`,
    "Bologna": `${basePath}Bologna.png`,
    "Sparta Prague": `${basePath}Sparta_Prague.png`,
    "Celtic": `${basePath}Celtic.png`,
    "Lille": `${basePath}Lille.png`,
    "Inter": `${basePath}Inter.png`,
    "Young Boys": `${basePath}Young_Boys.png`,
    "Aston Villa": `${basePath}Aston_Villa.png`,
    "Monaco": `${basePath}Monaco.png`,
    "Dinamo Zagreb": `${basePath}Dinamo_Zagreb.png`,
    "RB Salzburg": `${basePath}RB_Salzburg.png`,
    "Slovan Bratislava": `${basePath}Slovan_Bratislava.png`,
    "Shakhtar Donetsk": `${basePath}Shakhatar_Donetsk.png`,
    "Girona": `${basePath}Girona.png`,
    "Club Brugge": `${basePath}Club_Brugge.png`,
    "Bayren Leverkusen": `${basePath}Bayren_Leverkusen.png`,
    "Red Star": `${basePath}Red_Star.png`,
    "Strum Graz": `${basePath}Strum_Graz.png`,
    "Brest": `${basePath}Brest.png`,
    "Default": `${basePath}default_logo.png`
};

export default TEAM_LOGOS;
